# Generated by Django 5.0.4 on 2024-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptag',
            name='ip_network',
            field=models.GenericIPAddressField(),
        ),
    ]
