# Generated by Django 5.0.4 on 2024-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptags', '0002_alter_iptag_ip_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptag',
            name='ip_network',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
    ]
